language:
- php
php:
- 5.4
- 5.5
- 5.6
- 7.0
cache:
  directories:
  - vendor
before_script:
  - composer self-update
  - composer global require drupal/coder
  - composer global require "squizlabs/php_codesniffer=*"
  - phpenv rehash
  - phpcs --config-set installed_paths ~/.composer/vendor/drupal/coder/coder_sniffer
  - phpcs -i
script:
  - phpcs --standard=Drupal . --extensions=php,module,inc,install,test,profile,theme,css,info,txt,md
